[package]
name = "tracing-stackdriver"
version = "0.4.0"
authors = ["Alex Pearson <alex@alexpear.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/NAlexPear/tracing-stackdriver"
description = "Stackdriver-compatible tracing Subscriber"
keywords = ["tracing", "stackdriver", "logging"]

[badges.maintenance]
status = "actively-developed"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
doctest = false

[dependencies]
futures = "0.3.21"
Inflector = "0.11.4"
serde_json = "1.0.82"
tracing-core = "0.1.28"
tracing-futures = "0.2.5"
tracing-serde = "0.1.3"
thiserror = "1.0.31"

[dependencies.http]
optional = true
version = "0.2.8"

[dependencies.url]
optional = true
version = "2.2.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.138"

[dependencies.time]
default-features = false
version = "0.3.11"

[dependencies.tracing-subscriber]
features = ["json"]
version = "0.3.14"

[dependencies.valuable]
optional = true
features = ["derive"]
version = "0.1.0"

[dependencies.valuable-serde]
optional = true
version = "0.1.0"

[dev-dependencies]
lazy_static = "1.4.0"
tracing = "0.1.35"

[dev-dependencies.time]
features = ["serde", "serde-well-known"]
version = "0.3.11"

[features]
valuable = ["dep:valuable", "valuable-serde", "http", "url"]
